### ISSUE TITLE
SendMailService needs SignalSlot to overwrite variables in latest step

### ISSUE THREAD

**Issue by JBlocks** [einpraegsam/powermail_cond#22]
We have a lot of [signal slots in the extension](https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/SignalSlots/Index.html), but no way to overwrite the mail data in the latest part of the SendMailService before the real mail is send.

**Scenario:**
A customer fills the input field for email in the frontend form. The email should not trigger a real mail transport, because it is an test email address. (Frontend testing)

It must be possible to step into the sendmailservice with in signal hook, to overwrite or reset the senderEmail, receiverEmail, subject, etc.

Needs:
- Original Mail object with emailadress from the form field (email)
- Receiver/sender and subject data

A better solution is probably overriding the TypoScript settings (this-> settings ['receiver'] ['enable'] = 0). Overwriting the "$ this->settings" must then be possible via a signal slot in the FormController::createAction() based on the submitted form data (email input field).

**Comment by einpraegsam** [comment]
First of all, it seems that you're in the wrong github project (powermail_cond instead of powermail). In addition: The very last signal to stop mail sending is `sendTemplateEmailBeforeSend`. Testing the email-addresses on blacklisted strings, etc... shouldn't be that hard.
I'm sure there are several ways to fullfill your request.
